using Octokit;
using GhostDevOps.Gateway.Models;

namespace GhostDevOps.Gateway.Services;

// ─────────────────────────────────────────────────────────────────────────────
//  GitHubService — Week 3: The Automated PR Machine.
//
//  Flow:
//    1. Get the SHA of the main branch HEAD
//    2. Create a fix branch:  fix/ghost-{8-char-uuid}
//    3. Commit the AI-generated code to the target file
//    4. Open a Pull Request with a structured description
//    5. Return the PR URL for storage in the incident record
//
//  Security: This service holds the GitHub token. The LLM never sees it.
// ─────────────────────────────────────────────────────────────────────────────

public class GitHubService
{
    private readonly GitHubClient _client;
    private readonly string       _owner;
    private readonly string       _repo;
    private readonly ILogger<GitHubService> _logger;

    public GitHubService(IConfiguration config, ILogger<GitHubService> logger)
    {
        _logger = logger;
        _owner  = config["GitHub:Owner"]  ?? throw new InvalidOperationException("GitHub:Owner not configured");
        _repo   = config["GitHub:Repo"]   ?? throw new InvalidOperationException("GitHub:Repo not configured");
        var token = config["GitHub:Token"] ?? throw new InvalidOperationException("GitHub:Token not configured");

        _client = new GitHubClient(new ProductHeaderValue("ghost-devops-bot"))
        {
            Credentials = new Credentials(token)
        };
    }

    public async Task<string?> CreateAutoFixPRAsync(
        Incident  incident,
        string    targetFilePath,
        string    newFileContent,
        CancellationToken ct = default)
    {
        var branchName = $"fix/ghost-{incident.Id.ToString()[..8]}";

        try
        {
            // ── Step 1: Get main branch HEAD SHA ────────────────────────────
            _logger.LogInformation("Getting HEAD SHA for {Owner}/{Repo}", _owner, _repo);
            var mainRef = await _client.Git.Reference.Get(_owner, _repo, "heads/main");
            var headSha = mainRef.Object.Sha;

            // ── Step 2: Create fix branch ────────────────────────────────────
            _logger.LogInformation("Creating branch {Branch}", branchName);
            await _client.Git.Reference.Create(_owner, _repo,
                new NewReference($"refs/heads/{branchName}", headSha));

            // ── Step 3: Get existing file SHA (required for update) ──────────
            var existingFile = await _client.Repository.Content
                .GetAllContentsByRef(_owner, _repo, targetFilePath, "main");
            var fileSha = existingFile[0].Sha;

            // ── Step 4: Commit AI fix ────────────────────────────────────────
            _logger.LogInformation("Committing AI fix to {File} on {Branch}", targetFilePath, branchName);
            await _client.Repository.Content.UpdateFile(
                _owner, _repo, targetFilePath,
                new UpdateFileRequest(
                    message: $"fix: GhostDevOps auto-patch for incident {incident.Id.ToString()[..8]}\n\n" +
                             $"Root cause: {incident.RootCause}\n\n" +
                             "Generated by Ghost DevOps bot — reviewed by Safety Sandbox.",
                    content:  newFileContent,
                    sha:      fileSha,
                    branch:   branchName
                )
            );

            // ── Step 5: Open Pull Request ────────────────────────────────────
            _logger.LogInformation("Creating PR from {Branch} → main", branchName);
            var pr = await _client.Repository.PullRequest.Create(
                _owner, _repo,
                new NewPullRequest(
                    title: $"🤖 GhostDevOps: Auto-fix for {incident.AlertName}",
                    head:  branchName,
                    baseRef: "main"
                )
                {
                    Body = BuildPRBody(incident)
                }
            );

            _logger.LogInformation("PR created: {Url}", pr.HtmlUrl);
            return pr.HtmlUrl;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to create PR for incident {Id}", incident.Id);
            return null;
        }
    }

    private static string BuildPRBody(Incident incident) => $"""
        ## 🤖 Ghost DevOps Autonomous Fix

        **Incident ID:** `{incident.Id}`
        **Alert:** `{incident.AlertName}`
        **Service:** `{incident.Service}`
        **Detected:** {incident.DetectedAt:u}

        ---

        ### 🔍 Architect Analysis
        {incident.RootCause}

        ### 🛠️ Developer Fix
        {incident.ProposedFix}

        ---

        ### ✅ Safety Sandbox
        - ✅ Passed blocklist scan (no DROP, rm -rf, etc.)
        - ✅ AST analysis completed
        - ✅ Risk score within acceptable threshold

        > *This PR was generated autonomously by Ghost DevOps and has passed all pre-flight checks.*
        > *Human approval was {'required and granted' if incident.HumanApproved else 'not required for this risk level'}.*
        """;
}
